#!/usr/bin/python3
import numpy as np
from pylab import *
import matplotlib.style
import matplotlib.pyplot as plt
from matplotlib.ticker import AutoMinorLocator
from matplotlib import rc
import math

plt.style.use('classic')
plt.rcParams['axes.formatter.useoffset'] = False
plt.rc('font', size=18, **{'family': 'serif', 'serif': ['Computer Modern']})
plt.rc('text', usetex=True)
fig, ax = plt.subplots()


$0


# xtickloc = []
# plt.xticks(xtickloc)
ax.xaxis.set_minor_locator(AutoMinorLocator())
ax.yaxis.set_minor_locator(AutoMinorLocator())
plt.tick_params(axis='y', which='major', width=1, length=10, color='black')
plt.tick_params(axis='x', which='major', width=1, length=10, color='black')
plt.tick_params(axis='y', which='minor', width=1, length=4,  color='black', direction='in', bottom='on')
plt.tick_params(axis='x', which='minor', width=1, length=4,  color='black', direction='in', top='on')
plt.show()
